# local development docker compose
services:
  thaumaturgy-python:
    # Added to help with the dns timeouts
    extra_hosts:
      - "api.kessler.xyz:146.190.116.184"
      - "marker.kessler.xyz:209.38.71.2"
    build:
      context: ./thaumaturgy-python/
      dockerfile: ./Dockerfile
    env_file:
      - config/global.env
    environment:
      - MILVUS_DEV_DIR=/tmp/milvus/
    volumes:
      - ./thaumaturgy-python/:/app
      - ${VOLUMES_DIRECTORY:-./volumes}/instance:/app/instance
      - ${VOLUMES_DIRECTORY:-./volumes}/files:/files
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=thaumaturgy"
      - "traefik.http.routers.thaumaturgy-python.rule=PathPrefix(`/v1/`) "
      - "traefik.http.routers.thaumaturgy-python.rule=Host(`thaum.kessler.xyz`) && (PathPrefix(`/v1/`) || pathprefix(`/schema/`))"
      - "traefik.http.routers.thaumaturgy-python.entrypoints=websecure"
      - "traefik.http.routers.thaumaturgy-python.tls.certresolver=myresolver"
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5505"
      - "--workers"
      - "4"
      - "--reload"
    ports:
      - 5505:5505
    expose:
      - 5505

  valkey:
    hostname: valkey
    image: valkey/valkey:7.2.5
    volumes:
      - ./volumes/valkey.conf:/etc/valkey/valkey.conf
      - ./volumes/valkey-data:/data
    command: valkey-server /etc/valkey/valkey.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    expose:
      - 6379
