# local development docker compose
services:
  reverse-proxy:
    image: traefik:v3.1.2
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=nvenner@protonmail.ch"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker.constraints=Label(`traefik.namespace`,`litellm`)"
    expose:
      - 80
      - 443
    ports:
      - 2443:443
      - "${PROXY_UI_PORT:-8084}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${VOLUMES_DIRECTORY:-./volumes}/letsencrypt:/letsencrypt"
  frpc:
    image: snowdreamtech/frpc:alpine
    restart: always
    network_mode: "host"
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml
