# frpc.toml
serverAddr = "frps-testing.tail4a273.ts.net"
serverPort = 7000

# [[proxies]]
# name = "webserver-insecure"
# type = "http"
# localPort = 80
# customDomains = ["frpmedia.kessler.xyz"]

[[proxies]]
name = "webserver-secure"
type = "https"
localPort = 1443
localIP = "127.0.0.1"
customDomains = ["frpmedia.kessler.xyz"]
